##Add PostGres Container
##docker run --name swrpg-postgres -e POSTGRES_PASSWORD=mysecretpassword -d -p 5432:5432 postgres
# Use postgres/example user/password credentials
#PGDATA env var is the directory data gets stored in
#/docker-entrypoint-initdb.d

version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: swrpg
      POSTGRES_USER: swrpg
      POSTGRES_DB: swrpg
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment: 
      PGADMIN_DEFAULT_EMAIL: jseigel24@gmail.com
      PGADMIN_DEFAULT_PASSWORD: swrpg
    ports:
      - 2080:2080

##Add Web Services Container

